name: CI/CD for dev branch

on:
  pull_request:
    branches: [ dev ]
  push:
    branches: [ dev ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo test --verbose

  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/dev'
    needs: test
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo build --release
      - uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ vars.HOST_DEV }}
          port: ${{ vars.PORT_DEV }}
          username: ${{ secrets.USER_DEV }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          # proxy_host: ${{ secrets.PROXY_HOST }}
          # proxy_username: ${{ secrets.PROXY_USERNAME }}
          # proxy_key: ${{ secrets.PROXY_KEY }}
          # proxy_port: ${{ secrets.PROXY_PORT }}
          source: target/release/moku
          target: /usr/local/bin/
      - uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ vars.HOST_DEV }}
          port: ${{ vars.PORT_DEV }}
          username: ${{ secrets.USER_DEV }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          # proxy_host: ${{ secrets.PROXY_HOST }}
          # proxy_username: ${{ secrets.PROXY_USERNAME }}
          # proxy_key: ${{ secrets.PROXY_KEY }}
          # proxy_port: ${{ secrets.PROXY_PORT }}
          script: |
            sudo systemctl restart moku

